//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Patel_motorsEntities : DbContext
    {
        public Patel_motorsEntities()
            : base("name=Patel_motorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_login> admin_login { get; set; }
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<Quantity_Table> Quantity_Table { get; set; }
        public virtual DbSet<selling_product_table> selling_product_table { get; set; }
        public virtual DbSet<Purchse_OrderDetails> Purchse_OrderDetails { get; set; }
        public virtual DbSet<Selling_OrderDetails> Selling_OrderDetails { get; set; }
        public virtual DbSet<Selling_orders> Selling_orders { get; set; }
        public virtual DbSet<Purchase_orders> Purchase_orders { get; set; }
    }
}
