//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling_orders
    {
        public int order_id { get; set; }
        public string PartyName { get; set; }
        public string Invoice { get; set; }
        public string Date { get; set; }
    }
}
